DarkRP.RegisterSentences("kbrp_job_ranks", "de", {
	["policeRank1"] = "Anwärter",
	["policeRank2"] = "Meister",
	["policeRank3"] = "Obermeister",
	["policeRank4"] = "Hauptmeister",
	["policeRank5"] = "Kommissar",
	["policeRank6"] = "Oberkommissar",
	["policeRank7"] = "Hauptkommissar",
	["securityRank1"] ="Azubi",
	["securityRank2"] = "Türsteher",
	["securityRank3"] = "Sicherheitsfachkraft",
	["firefighterRank1"] = "Anwärter",
	["firefighterRank2"] = "Feuerwehrmann",
	["firefighterRank3"] = "Oberfeuerwehrmann",
	["firefighterRank4"] = "Hauptfeuerwehrmann",
	["firefighterRank5"] = "Löschmeister",
	["firefighterRank6"] = "Brandmeister",
	["firefighterRank7"] = "Oberbrandmeister",
	["firefighterRank8"] = "Kreisbrandmeister",
	["unknownRank"] = "Unbekannt",
	["cantChangePlayerXP"] = "Du kannst die XP von diesem Spieler nicht ändern!",
	["jobRequiredRank"] = "Du musst mindestens %s sein um %s zu werden.",
	["vehicleRequiredRank"] = "Du musst mindestens %s sein um auf dieses Fahrzeug zugreifen zu können."
})
