DarkRP.RegisterSentences("kbrp_equipment", "de", {
    ["takeEquipmentNotification"] = "Du hast dein Equipment ausgerüstet",
	["takeOffEquipmentNotification"] = "Du hast dein Equipment abgelegt",
	["frameTitle"] = "Kofferraum",
	["shieldSpeciality"] = "Schutzschild",
	["leftClickInstruction"] = "LINKSKLICK",
	["leftClickInstructionDescription"] = "Platzieren",
	["rightClickInstruction"] = "RECHTSKLICK",
	["rightClickInstructionDescription"] = "Abbrechen",
	["shieldHealth"] = "Schutzschild - HP,
	["shieldHealthDescription"] = "Zeigt den Status von deinem Schild an",
	["undoConstructionName"] = "Abbauen",
	["tooMuchPlayersInSameSpecialityNotification"] = "Die maximale Anzahl in diesem Bereich wurde erreicht",
	["assaultSpeciality"] = "Sturmgewehr",
	["shotgunSpeciality"] = "Shotgun",
	["sniperSpeciality"] = "Sniper",
	["welcomeSwatTitl"] = "WILLKOMMEN IM RAID",
	["welcomeSwatDescription"] = "Wähle deine Klasse",
	["chooseSpecialityButton"] = "Auswählen"
})
