DarkRP.RegisterSentences("kbrp_trunk", "de", {
    ["inventoryFrameTitle"] = "Dein Inventar",
	["dropItemOption"] = "Fallenlassen",
	["useItemOption"] = "Benutzen",
	["vehicleTrunkFrameTitle"] = "Kofferraum",
	["errorOccured"] = "Es ist ein Fehler aufgetreten, bitte versuche es erneut!",
	["trunkTooFar"] = "Du musst näher am Kofferaum sein!",
	["invalidItem"] = "Dieses Item existiert nicht",
	["errorOccured2"] = "Beim Hinzufügen dieses Items in deinen Kofferraum ist ein Fehler aufgetreten! (#1)",
	["vehicleBlacklisted"] = "Du kannst keine Items in dieses Fahrzeug legen!",
	["itemBlacklisted"] = "Du kannst dieses Item nicht in den Kofferraum legen!",
	["noEnoughTrunkPlace"] = "Es gibt nicht genug Platz im Kofferraum!",
	["equipWeapon"] = "Du rüstest deine Waffe aus...",
	["weaponEquiped"] = "Du hast deine Waffe ausgerüstet!",
	["trunkLocked"] = "Dieser Kofferraum ist abgeschlossen.",
	["tooMuchFoodBag"] = "Du hast die maximale Anzahl an Lebensmitteltaschen in deinem Kofferaum erreicht",
	["openTrunk"] = "KOFFERRAUM ÖFFNEN",
	["trunkDesc"] = "Drücke R um den Kofferaum zu öffnen",
})
