DarkRP.RegisterSentences("kbrp_astronaut", "fr", {
    ["npcName1"] = "Neil Amstrong",
	["npcName2"] = "Ham Strong",
	["npcName3"] = "Michael Collins",
	["invalidJobToTakeOff"] = "Vous n'avez pas le bon métier pour décoller",
	["takeOffTitle"] = "Décollage - ",
	["takeFlight"] = "Prendre la fusée",
	["takeOffInstruction1"] = "Préparation des propulseurs extèrieurs",
	["takeOffInstruction2"] = "Mise en place des freins",
	["takeOffInstruction3"] = "Check de la trajectoire globale",
	["takeOffInstruction4"] = "Ajustement des propulseurs",
	["takeOffInstruction5"] = "Mode manuel activé",
	["takeOffInstruction6"] = "Activation des sécurité de verouillage et d'assistance",
	["landingInProgressTitle"] = "Atterrissage en cours...",
	["landingInProgressDescription"] = "Nous sommes heureux de vous voir parmis nos voyageurs \n nous arrivons dans quelques secondes préparez vous",
	["waitBeforeTakeFlightAgain"] = "Attendez quelques secondes avant de reprendre un vol",
	["pnjTooFar"] = "Vous devez être plus proche du PNJ pour décoler",
	["cantDoThisActionOnMoon"] = "Vous ne pouvez pas faire spawn cela sur la Lune",
	["npcDesc"] = "Prendre la fusée",
	["landingInProgressDescription"] = "Nous sommes heureux de vous voir parmis nos voyageurs \n nous arrivons dans quelques secondes préparez vous.",
	["waitBeforeTakeFlightAgain"] = "Attendez quelques secondes avant de reprendre un vol !",
	["pnjTooFar"] = "Vous devez être plus proche du PNJ pour décoler !",
	["cantDoThisActionOnMoon"] = "Vous ne pouvez pas faire spawn cela sur la Lune !",
})
