DarkRP.RegisterSentences("kbrp_astronaut", "de", {
  ["npcName1"] = "Neil Amstrong",
	["npcName2"] = "Ham Strong",
	["npcName3"] = "Michael Collins",
	["invalidJobToTakeOff"] = "Du kannst die Rakete nicht mit diesem Beruf benutzen!",
	["takeOffTitle"] = "Flug - ",
	["takeFlight"] = "Abheben",
	["takeOffInstruction1"] = "Vorbereitung der Außentriebwerke",
	["takeOffInstruction2"] = "Bremse vorbereiten",
	["takeOffInstruction3"] = "Gang einstellen",
	["takeOffInstruction4"] = "Anpassen der Triebwerke",
	["takeOffInstruction5"] = "Autopilot aktivieren",
	["takeOffInstruction6"] = "Wir sind startklar, jetzt geht es los!",
	["landingInProgressTitle"] = "Landung wird durchgeführt...",
	["landingInProgressDescription"] = "Wir freuen uns, dass du mit uns reist. Wir sind gleich an unserem Zielort.",
	["waitBeforeTakeFlightAgain"] = "Warte einige Sekunden, bevor du wieder einen Flug antrittst!",
	["pnjTooFar"] = "Du musst näher am NPC sein, um zu loszufliegen!",
	["cantDoThisActionOnMoon"] = "Du kannst dies nicht auf dem Mond spawnen lassen!",
})
