DarkRP.RegisterSentences("kbrp_calendar", "fr", {
    ["cooldown"] = "Veuillez patienter avant d'essayer d'ouvrir une nouvelle caisse",
    ["comeAnOtherDay"] = "Reviens un autre jour pour ouvrir cette case",
    ["caseAlreadyOpenned"] = "Cette case a déjà été ouverte",
    ["error1"] = "Un problème est survenu avec l'ouverture, contacter un administrateur (#1)",
    ["noChance"] = "Ooops, Tu n'as rien gagné reviens demain pour retenter ta chance",
    ["winNotify"] = "Bravo champion, tu viens de gagner : %s",
    ["nothing"] = "Rien",
    ["mp9"] = "MP9",
    ["mp7"] = "MP7",
    ["l115"] = "L115",
    ["ar15"] = "AR15",
    ["p99"] = "P99",
    ["store1"] = "Vape Juicy (Non permanente)",
    ["store2"] = "Pack Couteaux (Non permanent)",
    ["store3"] = "Pack 1M",
    ["store4"] = "Pack Couteaux (Permanent)",
    ["store5"] = "Vape Juicy (Permanent)",
    ["money1"] = "5 000€",
    ["money2"] = "20 000€",
    ["money3"] = "50 000€",
    ["money4"] = "100 000€",
    ["vehicle"] = "Volkswagen New Beetle",
    ["vehicle1"] = "GMC Syclone",
    ["vehicle2"] = "Chevrolet Camaro SS 69",
    ["vehicle3"] = "Nissan GT-R",
    ["giftNotification"] = "%s vient de gagner un %s dans le calendrier de l'avent"
})
