DarkRP.RegisterSentences("kbrp_interaction", "de", {
    ["addItemInInventory"] = "In das Inventar aufnehmen",
	["addItemInTrunk"] = "In den Kofferraum legen",
	["openTrunk"] = "Kofferraum öffnen",
	["pushVehicle"] = "Fahrzeug schieben",
	["catchVehicle"] = "Fahrzeug ziehen",
	["butcherVehicle"] = "Tier häuten",
	["errorOccured"] = "Es ist ein Fehler aufgetreten! Bitte kontaktiere so schnell wie möglich ein Mitglied des Teams!",
	["invalidPermissions"] = "Das kannst du nicht tun!",
	["descAddInventory"] = "Gegenstand zum Inventar hinzufügen",
	["descAddTrunk"] = "Gegenstand in den Kofferaum legen",
	["descPushVehicle"] = "Fahrzeug anstossen",
	["descPullVehicle"] = "Fahrzeug ziehen",
	["descOpenTrunk"] = "Kofferraum öffnen",
	["descButcher"] = "Das Tier häuten",
	["takeOffEquipmentTitle"] = "Equipment ablegen",
	["takeOffEquipmentDescription"] = "Lege dein Equipment und deine Kleidung ab",
	["takeEquipmentTitle"] = "Equipment anlegen",
	["takeEquipmentDescription"] = "Lege dein Equipment und deine Kleidung an",
})
